#!/bin/bash

echo "🔍 Finding your Azure Container App URL..."
echo ""
echo "Method 1: Using Azure CLI (if installed)"
echo "Run this command:"
echo ""
echo "az containerapp show --name reviewers-backend-app --resource-group adzzat-reviewers-rg --query properties.configuration.ingress.fqdn -o tsv"
echo ""
echo "=================================="
echo ""
echo "Method 2: Azure Portal (Manual)"
echo "1. Go to: https://portal.azure.com"
echo "2. Search for 'Container Apps'"
echo "3. Click on 'reviewers-backend-app'"
echo "4. Copy the 'Application URL' from the Overview page"
echo "5. It will look like: https://reviewers-backend-app.XXXXXXXX.REGION.azurecontainerapps.io"
echo ""
echo "=================================="
echo ""
echo "Method 3: Check GitHub Actions Deployment Logs"
echo "1. Go to: https://github.com/niket-singh/Reviewers-Adzzat/actions"
echo "2. Find the latest successful backend deployment"
echo "3. Look for the Container App URL in the logs"
echo ""
